# This file contains application defaults
validator:
  database:
    host: 127.0.0.1
    name: hedera_validator
    password: validator_pass
    port: 5432
    username: validator
  clients:
    ethereum:
      block_confirmations: 5
      node_url:
      private_key:
      router_contract_address:
    hedera:
      operator:
        account_id:
        private_key:
      bridge_account:
      network_type: testnet
      payer_account:
      topic_id:
      fee_percentage: 10
      members:
    mirror_node:
      api_address: https://testnet.mirrornode.hedera.com/api/v1/
      client_address: hcs.testnet.mirrornode.hedera.com:5600
      max_retries: 10
      polling_interval: 5
  log_level: info
  port: 5200
  recovery:
    start_timestamp:
  rest-api-only: false