# This file contains application defaults
hedera:
  validator:
    db:
      host: 127.0.0.1
      name: hedera_validator
      password: validator_pass
      port: 5432
      username: validator
    port: 5200
  mirror_node:
    client: hcs.testnet.mirrornode.hedera.com:5600
    api_address: https://testnet.mirrornode.hedera.com/api/v1/
  client:
    network_type: testnet
    operator:
      account_id:
      private_key:
  watcher:
    crypto-transfer:
      accounts:
        - id: shard.realm.account
        - id: shard.realm.account
        - id: shard.realm.account
    consensus-message:
      topics:
        - id: shard.realm.topic
        - id: shard.realm.topic
        - id: shard.realm.topic