# This file contains application defaults
hedera:
  validator:
    db:
      host: 127.0.0.1
      name: hedera_validator
      password: validator_pass
      port: 5432
      username: validator
    port: 5200
  mirror_node:
    client_address: hcs.testnet.mirrornode.hedera.com:5600
    api_address: https://testnet.mirrornode.hedera.com/api/v1/
    polling_interval: 5000000000
  client:
    network_type: testnet
    operator:
      account_id:
      private_key:
  watcher:
    crypto-transfer:
      accounts:
    consensus-message:
      topics: