# This file contains application defaults
hedera:
  validator:
    db:
      host: 127.0.0.1
      name: hedera_validator
      password: validator_pass
      port: 5432
      username: validator
    port: 5200
  eth:
    infura_url:
  mirror_node:
    client_address: hcs.testnet.mirrornode.hedera.com:5600
    api_address: https://testnet.mirrornode.hedera.com/api/v1/
    polling_interval: 5
  client:
    network_type: testnet
    operator:
      account_id:
      private_key:
      eth_private_key:
  watcher:
    crypto-transfer:
      accounts:
    consensus-message:
      topics:
    eth:
      contract_address:
  handler:
    crypto-transfer:
      topic_id:
      polling_interval:
    consensus-message:
      addresses:
