hedera:
  network_type:
  dbs:
    - host:
      name:
      password:
      port:
      username:
    - host:
      name:
      password:
      port:
      username:
    - host:
      name:
      password:
      port:
      username:
  bridge_account:
  topic_id:
  fee_percentage: 10
  members:
  sender:
    account:
    private_key:
ethereum:
  node_url:
  router_contract_address:
  block_confirmations:
  private_key:
tokens:
  whbar: "HBAR"
  wtoken:
validator_url:
