# Template configuration for the e2e tests
hedera:
  network_type:
  db_validation:
    host:
    name:
    password: 
    port:
    username:
  bridge_account:
  topic_id:
  sender:
    account:
    private_key:
ethereum:
  node_url:
  contract_address:
tokens:
  whbar:
  wtoken:
validator_url:
