hedera:
  network_type:
  dbs:
    - host:
      name:
      password:
      port:
      username:
    - host:
      name:
      password:
      port:
      username:
    - host:
      name:
      password:
      port:
      username:
  bridge_account:
  topic_id:
  fee_percentage: 10000 # 10%
  members:
  sender:
    account:
    private_key:
  receiver:
    account:
    private_key:
  mirror_node:
    api_address:
    client_address:
    max_retries:
    polling_interval:
ethereum:
  client_configuration:
    node_url:
    router_contract_address:
    block_confirmations:
  sender:
    private_key:
  receiver:
    address:
tokens:
  whbar: "HBAR"
  wtoken:
validator_url:
